// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// ts_r.cpp
cpp11::list ts_reduce_(cpp11::integers unit, cpp11::doubles value, cpp11::doubles when, cpp11::doubles local, cpp11::sexp custom, cpp11::strings unit_names, std::string grain, int year_month, int year_day, cpp11::strings stats, double sampling_step);
extern "C" SEXP _timesift_ts_reduce_(SEXP unit, SEXP value, SEXP when, SEXP local, SEXP custom, SEXP unit_names, SEXP grain, SEXP year_month, SEXP year_day, SEXP stats, SEXP sampling_step) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_reduce_(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(unit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(value), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(when), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(local), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(custom), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(unit_names), cpp11::as_cpp<cpp11::decay_t<std::string>>(grain), cpp11::as_cpp<cpp11::decay_t<int>>(year_month), cpp11::as_cpp<cpp11::decay_t<int>>(year_day), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(stats), cpp11::as_cpp<cpp11::decay_t<double>>(sampling_step)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_coverage_(cpp11::integers unit, cpp11::doubles when, cpp11::doubles local, cpp11::sexp custom, cpp11::strings unit_names, std::string grain, int year_month, int year_day);
extern "C" SEXP _timesift_ts_coverage_(SEXP unit, SEXP when, SEXP local, SEXP custom, SEXP unit_names, SEXP grain, SEXP year_month, SEXP year_day) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_coverage_(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(unit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(when), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(local), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(custom), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(unit_names), cpp11::as_cpp<cpp11::decay_t<std::string>>(grain), cpp11::as_cpp<cpp11::decay_t<int>>(year_month), cpp11::as_cpp<cpp11::decay_t<int>>(year_day)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_reduce_lookbacks_(cpp11::integers unit, cpp11::doubles value, cpp11::doubles when, cpp11::doubles local, cpp11::strings unit_names, cpp11::integers target_unit, cpp11::doubles target_at, cpp11::strings target_names, double span, double lag, int bins, cpp11::strings stats);
extern "C" SEXP _timesift_ts_reduce_lookbacks_(SEXP unit, SEXP value, SEXP when, SEXP local, SEXP unit_names, SEXP target_unit, SEXP target_at, SEXP target_names, SEXP span, SEXP lag, SEXP bins, SEXP stats) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_reduce_lookbacks_(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(unit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(value), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(when), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(local), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(unit_names), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(target_unit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(target_at), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(target_names), cpp11::as_cpp<cpp11::decay_t<double>>(span), cpp11::as_cpp<cpp11::decay_t<double>>(lag), cpp11::as_cpp<cpp11::decay_t<int>>(bins), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(stats)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_bin_starts_(cpp11::doubles local, std::string grain, int year_month, int year_day);
extern "C" SEXP _timesift_ts_bin_starts_(SEXP local, SEXP grain, SEXP year_month, SEXP year_day) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_bin_starts_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(local), cpp11::as_cpp<cpp11::decay_t<std::string>>(grain), cpp11::as_cpp<cpp11::decay_t<int>>(year_month), cpp11::as_cpp<cpp11::decay_t<int>>(year_day)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_bin_nexts_(cpp11::doubles bins, std::string grain, int year_month, int year_day);
extern "C" SEXP _timesift_ts_bin_nexts_(SEXP bins, SEXP grain, SEXP year_month, SEXP year_day) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_bin_nexts_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(bins), cpp11::as_cpp<cpp11::decay_t<std::string>>(grain), cpp11::as_cpp<cpp11::decay_t<int>>(year_month), cpp11::as_cpp<cpp11::decay_t<int>>(year_day)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_year_fraction_(cpp11::doubles bin_start, cpp11::doubles bin_end);
extern "C" SEXP _timesift_ts_year_fraction_(SEXP bin_start, SEXP bin_end) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_year_fraction_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(bin_start), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(bin_end)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_year_phase_(cpp11::doubles bin_start, cpp11::doubles bin_end);
extern "C" SEXP _timesift_ts_year_phase_(SEXP bin_start, SEXP bin_end) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_year_phase_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(bin_start), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(bin_end)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_penalised_path_(cpp11::doubles x, cpp11::doubles y, cpp11::doubles w, int n, int p, std::string family, double alpha, int n_lambda, double lambda_min_ratio, cpp11::sexp lambda, double thresh, bool standardize, bool intercept, double max_pass);
extern "C" SEXP _timesift_ts_penalised_path_(SEXP x, SEXP y, SEXP w, SEXP n, SEXP p, SEXP family, SEXP alpha, SEXP n_lambda, SEXP lambda_min_ratio, SEXP lambda, SEXP thresh, SEXP standardize, SEXP intercept, SEXP max_pass) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_penalised_path_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(w), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<double>>(alpha), cpp11::as_cpp<cpp11::decay_t<int>>(n_lambda), cpp11::as_cpp<cpp11::decay_t<double>>(lambda_min_ratio), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(lambda), cpp11::as_cpp<cpp11::decay_t<double>>(thresh), cpp11::as_cpp<cpp11::decay_t<bool>>(standardize), cpp11::as_cpp<cpp11::decay_t<bool>>(intercept), cpp11::as_cpp<cpp11::decay_t<double>>(max_pass)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_penalised_cv_(cpp11::doubles x, cpp11::doubles y, cpp11::doubles w, int n, int p, std::string family, double alpha, int n_lambda, double lambda_min_ratio, cpp11::sexp lambda, double thresh, bool standardize, bool intercept, cpp11::integers fold, int n_fold, double max_pass, int threads);
extern "C" SEXP _timesift_ts_penalised_cv_(SEXP x, SEXP y, SEXP w, SEXP n, SEXP p, SEXP family, SEXP alpha, SEXP n_lambda, SEXP lambda_min_ratio, SEXP lambda, SEXP thresh, SEXP standardize, SEXP intercept, SEXP fold, SEXP n_fold, SEXP max_pass, SEXP threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_penalised_cv_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(w), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<double>>(alpha), cpp11::as_cpp<cpp11::decay_t<int>>(n_lambda), cpp11::as_cpp<cpp11::decay_t<double>>(lambda_min_ratio), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(lambda), cpp11::as_cpp<cpp11::decay_t<double>>(thresh), cpp11::as_cpp<cpp11::decay_t<bool>>(standardize), cpp11::as_cpp<cpp11::decay_t<bool>>(intercept), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(fold), cpp11::as_cpp<cpp11::decay_t<int>>(n_fold), cpp11::as_cpp<cpp11::decay_t<double>>(max_pass), cpp11::as_cpp<cpp11::decay_t<int>>(threads)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_penalised_predict_(cpp11::doubles lambda, cpp11::doubles a0, cpp11::doubles beta, std::string family, double at, cpp11::doubles newx, int n);
extern "C" SEXP _timesift_ts_penalised_predict_(SEXP lambda, SEXP a0, SEXP beta, SEXP family, SEXP at, SEXP newx, SEXP n) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_penalised_predict_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lambda), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(a0), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(beta), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<double>>(at), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(newx), cpp11::as_cpp<cpp11::decay_t<int>>(n)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_penalised_coef_(cpp11::doubles lambda, cpp11::doubles a0, cpp11::doubles beta, std::string family, double at);
extern "C" SEXP _timesift_ts_penalised_coef_(SEXP lambda, SEXP a0, SEXP beta, SEXP family, SEXP at) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_penalised_coef_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lambda), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(a0), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(beta), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<double>>(at)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_timesift_ts_bin_nexts_",         (DL_FUNC) &_timesift_ts_bin_nexts_,          4},
    {"_timesift_ts_bin_starts_",        (DL_FUNC) &_timesift_ts_bin_starts_,         4},
    {"_timesift_ts_coverage_",          (DL_FUNC) &_timesift_ts_coverage_,           8},
    {"_timesift_ts_penalised_coef_",    (DL_FUNC) &_timesift_ts_penalised_coef_,     5},
    {"_timesift_ts_penalised_cv_",      (DL_FUNC) &_timesift_ts_penalised_cv_,      17},
    {"_timesift_ts_penalised_path_",    (DL_FUNC) &_timesift_ts_penalised_path_,    14},
    {"_timesift_ts_penalised_predict_", (DL_FUNC) &_timesift_ts_penalised_predict_,  7},
    {"_timesift_ts_reduce_",            (DL_FUNC) &_timesift_ts_reduce_,            11},
    {"_timesift_ts_reduce_lookbacks_",  (DL_FUNC) &_timesift_ts_reduce_lookbacks_,  12},
    {"_timesift_ts_year_fraction_",     (DL_FUNC) &_timesift_ts_year_fraction_,      2},
    {"_timesift_ts_year_phase_",        (DL_FUNC) &_timesift_ts_year_phase_,         2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_timesift(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
