// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// ts_r.cpp
cpp11::list ts_reduce_(cpp11::integers unit, cpp11::doubles value, cpp11::doubles when, cpp11::doubles local, cpp11::sexp custom, cpp11::strings unit_names, std::string grain, int year_month, int year_day, cpp11::strings stats, double sampling_step);
extern "C" SEXP _timesift_ts_reduce_(SEXP unit, SEXP value, SEXP when, SEXP local, SEXP custom, SEXP unit_names, SEXP grain, SEXP year_month, SEXP year_day, SEXP stats, SEXP sampling_step) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_reduce_(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(unit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(value), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(when), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(local), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(custom), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(unit_names), cpp11::as_cpp<cpp11::decay_t<std::string>>(grain), cpp11::as_cpp<cpp11::decay_t<int>>(year_month), cpp11::as_cpp<cpp11::decay_t<int>>(year_day), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(stats), cpp11::as_cpp<cpp11::decay_t<double>>(sampling_step)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_coverage_(cpp11::integers unit, cpp11::doubles when, cpp11::doubles local, cpp11::sexp custom, cpp11::strings unit_names, std::string grain, int year_month, int year_day);
extern "C" SEXP _timesift_ts_coverage_(SEXP unit, SEXP when, SEXP local, SEXP custom, SEXP unit_names, SEXP grain, SEXP year_month, SEXP year_day) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_coverage_(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(unit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(when), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(local), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(custom), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(unit_names), cpp11::as_cpp<cpp11::decay_t<std::string>>(grain), cpp11::as_cpp<cpp11::decay_t<int>>(year_month), cpp11::as_cpp<cpp11::decay_t<int>>(year_day)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_reduce_lookbacks_(cpp11::integers unit, cpp11::doubles value, cpp11::doubles when, cpp11::doubles local, cpp11::strings unit_names, cpp11::integers target_unit, cpp11::doubles target_at, cpp11::strings target_names, double span, double lag, int bins, cpp11::strings stats);
extern "C" SEXP _timesift_ts_reduce_lookbacks_(SEXP unit, SEXP value, SEXP when, SEXP local, SEXP unit_names, SEXP target_unit, SEXP target_at, SEXP target_names, SEXP span, SEXP lag, SEXP bins, SEXP stats) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_reduce_lookbacks_(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(unit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(value), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(when), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(local), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(unit_names), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(target_unit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(target_at), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(target_names), cpp11::as_cpp<cpp11::decay_t<double>>(span), cpp11::as_cpp<cpp11::decay_t<double>>(lag), cpp11::as_cpp<cpp11::decay_t<int>>(bins), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(stats)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_bin_starts_(cpp11::doubles local, std::string grain, int year_month, int year_day);
extern "C" SEXP _timesift_ts_bin_starts_(SEXP local, SEXP grain, SEXP year_month, SEXP year_day) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_bin_starts_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(local), cpp11::as_cpp<cpp11::decay_t<std::string>>(grain), cpp11::as_cpp<cpp11::decay_t<int>>(year_month), cpp11::as_cpp<cpp11::decay_t<int>>(year_day)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_bin_nexts_(cpp11::doubles bins, std::string grain, int year_month, int year_day);
extern "C" SEXP _timesift_ts_bin_nexts_(SEXP bins, SEXP grain, SEXP year_month, SEXP year_day) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_bin_nexts_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(bins), cpp11::as_cpp<cpp11::decay_t<std::string>>(grain), cpp11::as_cpp<cpp11::decay_t<int>>(year_month), cpp11::as_cpp<cpp11::decay_t<int>>(year_day)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_cycle_fraction_(cpp11::doubles bin_start, cpp11::doubles bin_end, std::string cycle);
extern "C" SEXP _timesift_ts_cycle_fraction_(SEXP bin_start, SEXP bin_end, SEXP cycle) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_cycle_fraction_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(bin_start), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(bin_end), cpp11::as_cpp<cpp11::decay_t<std::string>>(cycle)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_cycle_phase_(cpp11::doubles bin_start, cpp11::doubles bin_end, std::string cycle);
extern "C" SEXP _timesift_ts_cycle_phase_(SEXP bin_start, SEXP bin_end, SEXP cycle) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_cycle_phase_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(bin_start), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(bin_end), cpp11::as_cpp<cpp11::decay_t<std::string>>(cycle)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_penalised_path_(cpp11::doubles x, cpp11::doubles y, cpp11::doubles w, int n, int p, std::string family, double alpha, int n_lambda, double lambda_min_ratio, cpp11::sexp lambda, double thresh, bool standardize, bool intercept, double max_pass);
extern "C" SEXP _timesift_ts_penalised_path_(SEXP x, SEXP y, SEXP w, SEXP n, SEXP p, SEXP family, SEXP alpha, SEXP n_lambda, SEXP lambda_min_ratio, SEXP lambda, SEXP thresh, SEXP standardize, SEXP intercept, SEXP max_pass) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_penalised_path_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(w), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<double>>(alpha), cpp11::as_cpp<cpp11::decay_t<int>>(n_lambda), cpp11::as_cpp<cpp11::decay_t<double>>(lambda_min_ratio), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(lambda), cpp11::as_cpp<cpp11::decay_t<double>>(thresh), cpp11::as_cpp<cpp11::decay_t<bool>>(standardize), cpp11::as_cpp<cpp11::decay_t<bool>>(intercept), cpp11::as_cpp<cpp11::decay_t<double>>(max_pass)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_penalised_cv_(cpp11::doubles x, cpp11::doubles y, cpp11::doubles w, int n, int p, int r, std::string family, double alpha, int n_lambda, double lambda_min_ratio, cpp11::sexp lambda, double thresh, bool standardize, bool intercept, cpp11::sexp fold, cpp11::integers n_fold, double max_pass, int threads);
extern "C" SEXP _timesift_ts_penalised_cv_(SEXP x, SEXP y, SEXP w, SEXP n, SEXP p, SEXP r, SEXP family, SEXP alpha, SEXP n_lambda, SEXP lambda_min_ratio, SEXP lambda, SEXP thresh, SEXP standardize, SEXP intercept, SEXP fold, SEXP n_fold, SEXP max_pass, SEXP threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_penalised_cv_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(w), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(r), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<double>>(alpha), cpp11::as_cpp<cpp11::decay_t<int>>(n_lambda), cpp11::as_cpp<cpp11::decay_t<double>>(lambda_min_ratio), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(lambda), cpp11::as_cpp<cpp11::decay_t<double>>(thresh), cpp11::as_cpp<cpp11::decay_t<bool>>(standardize), cpp11::as_cpp<cpp11::decay_t<bool>>(intercept), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(fold), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(n_fold), cpp11::as_cpp<cpp11::decay_t<double>>(max_pass), cpp11::as_cpp<cpp11::decay_t<int>>(threads)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_penalised_predict_(cpp11::doubles lambda, cpp11::doubles a0, cpp11::doubles beta, std::string family, double at, cpp11::doubles newx, int n);
extern "C" SEXP _timesift_ts_penalised_predict_(SEXP lambda, SEXP a0, SEXP beta, SEXP family, SEXP at, SEXP newx, SEXP n) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_penalised_predict_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lambda), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(a0), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(beta), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<double>>(at), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(newx), cpp11::as_cpp<cpp11::decay_t<int>>(n)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_penalised_coef_(cpp11::doubles lambda, cpp11::doubles a0, cpp11::doubles beta, std::string family, double at);
extern "C" SEXP _timesift_ts_penalised_coef_(SEXP lambda, SEXP a0, SEXP beta, SEXP family, SEXP at) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_penalised_coef_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lambda), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(a0), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(beta), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<double>>(at)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_tree_fit_(cpp11::doubles x, cpp11::doubles y, cpp11::doubles w, int n, int p, int r, std::string family, int min_split, int min_leaf, double cp, int max_depth, double shrink, cpp11::sexp fold, cpp11::integers n_fold, int threads);
extern "C" SEXP _timesift_ts_tree_fit_(SEXP x, SEXP y, SEXP w, SEXP n, SEXP p, SEXP r, SEXP family, SEXP min_split, SEXP min_leaf, SEXP cp, SEXP max_depth, SEXP shrink, SEXP fold, SEXP n_fold, SEXP threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_tree_fit_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(w), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(r), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<int>>(min_split), cpp11::as_cpp<cpp11::decay_t<int>>(min_leaf), cpp11::as_cpp<cpp11::decay_t<double>>(cp), cpp11::as_cpp<cpp11::decay_t<int>>(max_depth), cpp11::as_cpp<cpp11::decay_t<double>>(shrink), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(fold), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(n_fold), cpp11::as_cpp<cpp11::decay_t<int>>(threads)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_tree_prune_(cpp11::list tree, double cp);
extern "C" SEXP _timesift_ts_tree_prune_(SEXP tree, SEXP cp) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_tree_prune_(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(tree), cpp11::as_cpp<cpp11::decay_t<double>>(cp)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_tree_predict_(cpp11::list tree, cpp11::doubles newx, int n, int p);
extern "C" SEXP _timesift_ts_tree_predict_(SEXP tree, SEXP newx, SEXP n, SEXP p) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_tree_predict_(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(tree), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(newx), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_forest_fit_(cpp11::doubles x, cpp11::doubles y, cpp11::doubles w, int n, int p, int r, std::string family, int trees, int mtry, int min_leaf, bool balance, cpp11::doubles seeds, int threads);
extern "C" SEXP _timesift_ts_forest_fit_(SEXP x, SEXP y, SEXP w, SEXP n, SEXP p, SEXP r, SEXP family, SEXP trees, SEXP mtry, SEXP min_leaf, SEXP balance, SEXP seeds, SEXP threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_forest_fit_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(w), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(r), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<int>>(trees), cpp11::as_cpp<cpp11::decay_t<int>>(mtry), cpp11::as_cpp<cpp11::decay_t<int>>(min_leaf), cpp11::as_cpp<cpp11::decay_t<bool>>(balance), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(seeds), cpp11::as_cpp<cpp11::decay_t<int>>(threads)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_forest_predict_(cpp11::list forest, cpp11::doubles newx, int n, int p);
extern "C" SEXP _timesift_ts_forest_predict_(SEXP forest, SEXP newx, SEXP n, SEXP p) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_forest_predict_(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(forest), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(newx), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_boost_fit_(cpp11::doubles x, cpp11::doubles y, cpp11::doubles w, int n, int p, int r, std::string family, int trees, int depth, double shrinkage, double min_leaf, double subsample, double colsample, bool newton, double lambda, double gamma, cpp11::doubles seeds, cpp11::sexp fold, cpp11::integers n_fold, int threads);
extern "C" SEXP _timesift_ts_boost_fit_(SEXP x, SEXP y, SEXP w, SEXP n, SEXP p, SEXP r, SEXP family, SEXP trees, SEXP depth, SEXP shrinkage, SEXP min_leaf, SEXP subsample, SEXP colsample, SEXP newton, SEXP lambda, SEXP gamma, SEXP seeds, SEXP fold, SEXP n_fold, SEXP threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_boost_fit_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(w), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(r), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<int>>(trees), cpp11::as_cpp<cpp11::decay_t<int>>(depth), cpp11::as_cpp<cpp11::decay_t<double>>(shrinkage), cpp11::as_cpp<cpp11::decay_t<double>>(min_leaf), cpp11::as_cpp<cpp11::decay_t<double>>(subsample), cpp11::as_cpp<cpp11::decay_t<double>>(colsample), cpp11::as_cpp<cpp11::decay_t<bool>>(newton), cpp11::as_cpp<cpp11::decay_t<double>>(lambda), cpp11::as_cpp<cpp11::decay_t<double>>(gamma), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(seeds), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(fold), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(n_fold), cpp11::as_cpp<cpp11::decay_t<int>>(threads)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_boost_predict_(cpp11::list fit, cpp11::doubles newx, int n, int p);
extern "C" SEXP _timesift_ts_boost_predict_(SEXP fit, SEXP newx, SEXP n, SEXP p) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_boost_predict_(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(fit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(newx), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_forest_stream_(double seed, double tree, int n);
extern "C" SEXP _timesift_ts_forest_stream_(SEXP seed, SEXP tree, SEXP n) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_forest_stream_(cpp11::as_cpp<cpp11::decay_t<double>>(seed), cpp11::as_cpp<cpp11::decay_t<double>>(tree), cpp11::as_cpp<cpp11::decay_t<int>>(n)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_maxnet_design_(cpp11::doubles x, cpp11::doubles y, int n, int p, std::string classes, int knots, double regmult, std::string formulation, bool add_samples, double max_design);
extern "C" SEXP _timesift_ts_maxnet_design_(SEXP x, SEXP y, SEXP n, SEXP p, SEXP classes, SEXP knots, SEXP regmult, SEXP formulation, SEXP add_samples, SEXP max_design) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_maxnet_design_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<std::string>>(classes), cpp11::as_cpp<cpp11::decay_t<int>>(knots), cpp11::as_cpp<cpp11::decay_t<double>>(regmult), cpp11::as_cpp<cpp11::decay_t<std::string>>(formulation), cpp11::as_cpp<cpp11::decay_t<bool>>(add_samples), cpp11::as_cpp<cpp11::decay_t<double>>(max_design)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_maxnet_fit_(cpp11::doubles x, cpp11::doubles y, cpp11::doubles w, int n, int p, int r, std::string classes, int knots, double regmult, std::string formulation, bool add_samples, double thresh, double max_pass, int n_lambda, bool one_se, cpp11::sexp fold, cpp11::integers n_fold, int threads, double max_design);
extern "C" SEXP _timesift_ts_maxnet_fit_(SEXP x, SEXP y, SEXP w, SEXP n, SEXP p, SEXP r, SEXP classes, SEXP knots, SEXP regmult, SEXP formulation, SEXP add_samples, SEXP thresh, SEXP max_pass, SEXP n_lambda, SEXP one_se, SEXP fold, SEXP n_fold, SEXP threads, SEXP max_design) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_maxnet_fit_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(w), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(r), cpp11::as_cpp<cpp11::decay_t<std::string>>(classes), cpp11::as_cpp<cpp11::decay_t<int>>(knots), cpp11::as_cpp<cpp11::decay_t<double>>(regmult), cpp11::as_cpp<cpp11::decay_t<std::string>>(formulation), cpp11::as_cpp<cpp11::decay_t<bool>>(add_samples), cpp11::as_cpp<cpp11::decay_t<double>>(thresh), cpp11::as_cpp<cpp11::decay_t<double>>(max_pass), cpp11::as_cpp<cpp11::decay_t<int>>(n_lambda), cpp11::as_cpp<cpp11::decay_t<bool>>(one_se), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(fold), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(n_fold), cpp11::as_cpp<cpp11::decay_t<int>>(threads), cpp11::as_cpp<cpp11::decay_t<double>>(max_design)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_maxnet_predict_(cpp11::list fit, cpp11::doubles newx, int n, int p, bool clamp, std::string type);
extern "C" SEXP _timesift_ts_maxnet_predict_(SEXP fit, SEXP newx, SEXP n, SEXP p, SEXP clamp, SEXP type) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_maxnet_predict_(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(fit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(newx), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<bool>>(clamp), cpp11::as_cpp<cpp11::decay_t<std::string>>(type)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_envelope_fit_(cpp11::doubles x, cpp11::doubles y, int n, int p, double quantile);
extern "C" SEXP _timesift_ts_envelope_fit_(SEXP x, SEXP y, SEXP n, SEXP p, SEXP quantile) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_envelope_fit_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<double>>(quantile)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_envelope_predict_(cpp11::list fit, cpp11::doubles newx, int n, int p);
extern "C" SEXP _timesift_ts_envelope_predict_(SEXP fit, SEXP newx, SEXP n, SEXP p) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_envelope_predict_(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(fit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(newx), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_stepwise_fit_(cpp11::doubles x, cpp11::doubles y, cpp11::doubles w, int n, int p, int r, std::string family, double max_terms, int degree, std::string direction, std::string terms, int threads);
extern "C" SEXP _timesift_ts_stepwise_fit_(SEXP x, SEXP y, SEXP w, SEXP n, SEXP p, SEXP r, SEXP family, SEXP max_terms, SEXP degree, SEXP direction, SEXP terms, SEXP threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_stepwise_fit_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(w), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(r), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<double>>(max_terms), cpp11::as_cpp<cpp11::decay_t<int>>(degree), cpp11::as_cpp<cpp11::decay_t<std::string>>(direction), cpp11::as_cpp<cpp11::decay_t<std::string>>(terms), cpp11::as_cpp<cpp11::decay_t<int>>(threads)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_stepwise_predict_(cpp11::list fit, cpp11::doubles newx, int n, int p);
extern "C" SEXP _timesift_ts_stepwise_predict_(SEXP fit, SEXP newx, SEXP n, SEXP p) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_stepwise_predict_(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(fit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(newx), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_mars_fit_(cpp11::doubles x, cpp11::doubles y, cpp11::doubles w, int n, int p, int r, std::string family, int degree, double penalty, int nk, double thresh, int minspan, int endspan, int fast_k, double fast_beta, bool prune, int nprune, int threads);
extern "C" SEXP _timesift_ts_mars_fit_(SEXP x, SEXP y, SEXP w, SEXP n, SEXP p, SEXP r, SEXP family, SEXP degree, SEXP penalty, SEXP nk, SEXP thresh, SEXP minspan, SEXP endspan, SEXP fast_k, SEXP fast_beta, SEXP prune, SEXP nprune, SEXP threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_mars_fit_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(w), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(r), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<int>>(degree), cpp11::as_cpp<cpp11::decay_t<double>>(penalty), cpp11::as_cpp<cpp11::decay_t<int>>(nk), cpp11::as_cpp<cpp11::decay_t<double>>(thresh), cpp11::as_cpp<cpp11::decay_t<int>>(minspan), cpp11::as_cpp<cpp11::decay_t<int>>(endspan), cpp11::as_cpp<cpp11::decay_t<int>>(fast_k), cpp11::as_cpp<cpp11::decay_t<double>>(fast_beta), cpp11::as_cpp<cpp11::decay_t<bool>>(prune), cpp11::as_cpp<cpp11::decay_t<int>>(nprune), cpp11::as_cpp<cpp11::decay_t<int>>(threads)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_mars_predict_(cpp11::list fit, cpp11::doubles newx, int n, int p);
extern "C" SEXP _timesift_ts_mars_predict_(SEXP fit, SEXP newx, SEXP n, SEXP p) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_mars_predict_(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(fit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(newx), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_perceptron_fit_(cpp11::doubles x, cpp11::doubles y, cpp11::doubles w, int n, int p, int r, cpp11::integers seeds, std::string family, int hidden, bool skip, bool standardise, double decay, double range, int max_iter, double abs_tol, double rel_tol, int threads, cpp11::doubles start);
extern "C" SEXP _timesift_ts_perceptron_fit_(SEXP x, SEXP y, SEXP w, SEXP n, SEXP p, SEXP r, SEXP seeds, SEXP family, SEXP hidden, SEXP skip, SEXP standardise, SEXP decay, SEXP range, SEXP max_iter, SEXP abs_tol, SEXP rel_tol, SEXP threads, SEXP start) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_perceptron_fit_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(w), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(r), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(seeds), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<int>>(hidden), cpp11::as_cpp<cpp11::decay_t<bool>>(skip), cpp11::as_cpp<cpp11::decay_t<bool>>(standardise), cpp11::as_cpp<cpp11::decay_t<double>>(decay), cpp11::as_cpp<cpp11::decay_t<double>>(range), cpp11::as_cpp<cpp11::decay_t<int>>(max_iter), cpp11::as_cpp<cpp11::decay_t<double>>(abs_tol), cpp11::as_cpp<cpp11::decay_t<double>>(rel_tol), cpp11::as_cpp<cpp11::decay_t<int>>(threads), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(start)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_perceptron_predict_(cpp11::list fit, cpp11::doubles newx, int n, int p);
extern "C" SEXP _timesift_ts_perceptron_predict_(SEXP fit, SEXP newx, SEXP n, SEXP p) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_perceptron_predict_(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(fit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(newx), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_fda_fit_(cpp11::doubles x, cpp11::doubles y, cpp11::doubles w, int n, int p, int r, int degree, double penalty, int nk, double thresh, bool prune, bool calibrate, int threads);
extern "C" SEXP _timesift_ts_fda_fit_(SEXP x, SEXP y, SEXP w, SEXP n, SEXP p, SEXP r, SEXP degree, SEXP penalty, SEXP nk, SEXP thresh, SEXP prune, SEXP calibrate, SEXP threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_fda_fit_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(w), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(r), cpp11::as_cpp<cpp11::decay_t<int>>(degree), cpp11::as_cpp<cpp11::decay_t<double>>(penalty), cpp11::as_cpp<cpp11::decay_t<int>>(nk), cpp11::as_cpp<cpp11::decay_t<double>>(thresh), cpp11::as_cpp<cpp11::decay_t<bool>>(prune), cpp11::as_cpp<cpp11::decay_t<bool>>(calibrate), cpp11::as_cpp<cpp11::decay_t<int>>(threads)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_fda_predict_(cpp11::list fit, cpp11::doubles newx, int n, int p);
extern "C" SEXP _timesift_ts_fda_predict_(SEXP fit, SEXP newx, SEXP n, SEXP p) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_fda_predict_(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(fit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(newx), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_additive_fit_(cpp11::doubles x, cpp11::doubles y, cpp11::doubles w, int n, int p, int r, std::string family, int k, double gamma, int max_knots, int threads, cpp11::doubles sp);
extern "C" SEXP _timesift_ts_additive_fit_(SEXP x, SEXP y, SEXP w, SEXP n, SEXP p, SEXP r, SEXP family, SEXP k, SEXP gamma, SEXP max_knots, SEXP threads, SEXP sp) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_additive_fit_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(w), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(r), cpp11::as_cpp<cpp11::decay_t<std::string>>(family), cpp11::as_cpp<cpp11::decay_t<int>>(k), cpp11::as_cpp<cpp11::decay_t<double>>(gamma), cpp11::as_cpp<cpp11::decay_t<int>>(max_knots), cpp11::as_cpp<cpp11::decay_t<int>>(threads), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(sp)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_additive_predict_(cpp11::list fit, cpp11::doubles newx, int n, int p);
extern "C" SEXP _timesift_ts_additive_predict_(SEXP fit, SEXP newx, SEXP n, SEXP p) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_additive_predict_(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(fit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(newx), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p)));
  END_CPP11
}
// ts_r.cpp
cpp11::list ts_hierarchical_fit_(cpp11::doubles x, cpp11::doubles y, cpp11::doubles w, int n, int p, cpp11::sexp unit, int n_unit, cpp11::sexp coords, std::string field, double beta_sd, double sd_u, double sd_alpha, double range_fraction, double range_alpha, int m, double boundary, int neighbours, int cov, int nodes, double step, int threads, cpp11::sexp theta);
extern "C" SEXP _timesift_ts_hierarchical_fit_(SEXP x, SEXP y, SEXP w, SEXP n, SEXP p, SEXP unit, SEXP n_unit, SEXP coords, SEXP field, SEXP beta_sd, SEXP sd_u, SEXP sd_alpha, SEXP range_fraction, SEXP range_alpha, SEXP m, SEXP boundary, SEXP neighbours, SEXP cov, SEXP nodes, SEXP step, SEXP threads, SEXP theta) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_hierarchical_fit_(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(w), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(unit), cpp11::as_cpp<cpp11::decay_t<int>>(n_unit), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(coords), cpp11::as_cpp<cpp11::decay_t<std::string>>(field), cpp11::as_cpp<cpp11::decay_t<double>>(beta_sd), cpp11::as_cpp<cpp11::decay_t<double>>(sd_u), cpp11::as_cpp<cpp11::decay_t<double>>(sd_alpha), cpp11::as_cpp<cpp11::decay_t<double>>(range_fraction), cpp11::as_cpp<cpp11::decay_t<double>>(range_alpha), cpp11::as_cpp<cpp11::decay_t<int>>(m), cpp11::as_cpp<cpp11::decay_t<double>>(boundary), cpp11::as_cpp<cpp11::decay_t<int>>(neighbours), cpp11::as_cpp<cpp11::decay_t<int>>(cov), cpp11::as_cpp<cpp11::decay_t<int>>(nodes), cpp11::as_cpp<cpp11::decay_t<double>>(step), cpp11::as_cpp<cpp11::decay_t<int>>(threads), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(theta)));
  END_CPP11
}
// ts_r.cpp
cpp11::doubles ts_hierarchical_predict_(cpp11::list fit, cpp11::doubles newx, int n, int p, cpp11::sexp unit, cpp11::sexp coords);
extern "C" SEXP _timesift_ts_hierarchical_predict_(SEXP fit, SEXP newx, SEXP n, SEXP p, SEXP unit, SEXP coords) {
  BEGIN_CPP11
    return cpp11::as_sexp(ts_hierarchical_predict_(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(fit), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(newx), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(p), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(unit), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(coords)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_timesift_ts_additive_fit_",         (DL_FUNC) &_timesift_ts_additive_fit_,         12},
    {"_timesift_ts_additive_predict_",     (DL_FUNC) &_timesift_ts_additive_predict_,      4},
    {"_timesift_ts_bin_nexts_",            (DL_FUNC) &_timesift_ts_bin_nexts_,             4},
    {"_timesift_ts_bin_starts_",           (DL_FUNC) &_timesift_ts_bin_starts_,            4},
    {"_timesift_ts_boost_fit_",            (DL_FUNC) &_timesift_ts_boost_fit_,            20},
    {"_timesift_ts_boost_predict_",        (DL_FUNC) &_timesift_ts_boost_predict_,         4},
    {"_timesift_ts_coverage_",             (DL_FUNC) &_timesift_ts_coverage_,              8},
    {"_timesift_ts_cycle_fraction_",       (DL_FUNC) &_timesift_ts_cycle_fraction_,        3},
    {"_timesift_ts_cycle_phase_",          (DL_FUNC) &_timesift_ts_cycle_phase_,           3},
    {"_timesift_ts_envelope_fit_",         (DL_FUNC) &_timesift_ts_envelope_fit_,          5},
    {"_timesift_ts_envelope_predict_",     (DL_FUNC) &_timesift_ts_envelope_predict_,      4},
    {"_timesift_ts_fda_fit_",              (DL_FUNC) &_timesift_ts_fda_fit_,              13},
    {"_timesift_ts_fda_predict_",          (DL_FUNC) &_timesift_ts_fda_predict_,           4},
    {"_timesift_ts_forest_fit_",           (DL_FUNC) &_timesift_ts_forest_fit_,           13},
    {"_timesift_ts_forest_predict_",       (DL_FUNC) &_timesift_ts_forest_predict_,        4},
    {"_timesift_ts_forest_stream_",        (DL_FUNC) &_timesift_ts_forest_stream_,         3},
    {"_timesift_ts_hierarchical_fit_",     (DL_FUNC) &_timesift_ts_hierarchical_fit_,     22},
    {"_timesift_ts_hierarchical_predict_", (DL_FUNC) &_timesift_ts_hierarchical_predict_,  6},
    {"_timesift_ts_mars_fit_",             (DL_FUNC) &_timesift_ts_mars_fit_,             18},
    {"_timesift_ts_mars_predict_",         (DL_FUNC) &_timesift_ts_mars_predict_,          4},
    {"_timesift_ts_maxnet_design_",        (DL_FUNC) &_timesift_ts_maxnet_design_,        10},
    {"_timesift_ts_maxnet_fit_",           (DL_FUNC) &_timesift_ts_maxnet_fit_,           19},
    {"_timesift_ts_maxnet_predict_",       (DL_FUNC) &_timesift_ts_maxnet_predict_,        6},
    {"_timesift_ts_penalised_coef_",       (DL_FUNC) &_timesift_ts_penalised_coef_,        5},
    {"_timesift_ts_penalised_cv_",         (DL_FUNC) &_timesift_ts_penalised_cv_,         18},
    {"_timesift_ts_penalised_path_",       (DL_FUNC) &_timesift_ts_penalised_path_,       14},
    {"_timesift_ts_penalised_predict_",    (DL_FUNC) &_timesift_ts_penalised_predict_,     7},
    {"_timesift_ts_perceptron_fit_",       (DL_FUNC) &_timesift_ts_perceptron_fit_,       18},
    {"_timesift_ts_perceptron_predict_",   (DL_FUNC) &_timesift_ts_perceptron_predict_,    4},
    {"_timesift_ts_reduce_",               (DL_FUNC) &_timesift_ts_reduce_,               11},
    {"_timesift_ts_reduce_lookbacks_",     (DL_FUNC) &_timesift_ts_reduce_lookbacks_,     12},
    {"_timesift_ts_stepwise_fit_",         (DL_FUNC) &_timesift_ts_stepwise_fit_,         12},
    {"_timesift_ts_stepwise_predict_",     (DL_FUNC) &_timesift_ts_stepwise_predict_,      4},
    {"_timesift_ts_tree_fit_",             (DL_FUNC) &_timesift_ts_tree_fit_,             15},
    {"_timesift_ts_tree_predict_",         (DL_FUNC) &_timesift_ts_tree_predict_,          4},
    {"_timesift_ts_tree_prune_",           (DL_FUNC) &_timesift_ts_tree_prune_,            2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_timesift(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
