# Generated by cpp11: do not edit by hand

ts_reduce_ <- function(unit, value, when, local, custom, unit_names, grain, year_month, year_day, stats, sampling_step) {
  .Call(`_timesift_ts_reduce_`, unit, value, when, local, custom, unit_names, grain, year_month, year_day, stats, sampling_step)
}

ts_coverage_ <- function(unit, when, local, custom, unit_names, grain, year_month, year_day) {
  .Call(`_timesift_ts_coverage_`, unit, when, local, custom, unit_names, grain, year_month, year_day)
}

ts_reduce_lookbacks_ <- function(unit, value, when, local, unit_names, target_unit, target_at, target_names, span, lag, bins, stats) {
  .Call(`_timesift_ts_reduce_lookbacks_`, unit, value, when, local, unit_names, target_unit, target_at, target_names, span, lag, bins, stats)
}

ts_bin_starts_ <- function(local, grain, year_month, year_day) {
  .Call(`_timesift_ts_bin_starts_`, local, grain, year_month, year_day)
}

ts_bin_nexts_ <- function(bins, grain, year_month, year_day) {
  .Call(`_timesift_ts_bin_nexts_`, bins, grain, year_month, year_day)
}

ts_cycle_fraction_ <- function(bin_start, bin_end, cycle) {
  .Call(`_timesift_ts_cycle_fraction_`, bin_start, bin_end, cycle)
}

ts_cycle_phase_ <- function(bin_start, bin_end, cycle) {
  .Call(`_timesift_ts_cycle_phase_`, bin_start, bin_end, cycle)
}

ts_penalised_path_ <- function(x, y, w, n, p, family, alpha, n_lambda, lambda_min_ratio, lambda, thresh, standardize, intercept, max_pass) {
  .Call(`_timesift_ts_penalised_path_`, x, y, w, n, p, family, alpha, n_lambda, lambda_min_ratio, lambda, thresh, standardize, intercept, max_pass)
}

ts_penalised_cv_ <- function(x, y, w, n, p, family, alpha, n_lambda, lambda_min_ratio, lambda, thresh, standardize, intercept, fold, n_fold, max_pass, threads) {
  .Call(`_timesift_ts_penalised_cv_`, x, y, w, n, p, family, alpha, n_lambda, lambda_min_ratio, lambda, thresh, standardize, intercept, fold, n_fold, max_pass, threads)
}

ts_penalised_predict_ <- function(lambda, a0, beta, family, at, newx, n) {
  .Call(`_timesift_ts_penalised_predict_`, lambda, a0, beta, family, at, newx, n)
}

ts_penalised_coef_ <- function(lambda, a0, beta, family, at) {
  .Call(`_timesift_ts_penalised_coef_`, lambda, a0, beta, family, at)
}

ts_tree_fit_ <- function(x, y, w, n, p, family, min_split, min_leaf, cp, max_depth, shrink, fold, n_fold) {
  .Call(`_timesift_ts_tree_fit_`, x, y, w, n, p, family, min_split, min_leaf, cp, max_depth, shrink, fold, n_fold)
}

ts_tree_prune_ <- function(tree, cp) {
  .Call(`_timesift_ts_tree_prune_`, tree, cp)
}

ts_tree_predict_ <- function(tree, newx, n, p) {
  .Call(`_timesift_ts_tree_predict_`, tree, newx, n, p)
}

ts_forest_fit_ <- function(x, y, w, n, p, family, trees, mtry, min_leaf, balance, seed, threads) {
  .Call(`_timesift_ts_forest_fit_`, x, y, w, n, p, family, trees, mtry, min_leaf, balance, seed, threads)
}

ts_forest_predict_ <- function(forest, newx, n, p) {
  .Call(`_timesift_ts_forest_predict_`, forest, newx, n, p)
}

ts_boost_fit_ <- function(x, y, w, n, p, family, trees, depth, shrinkage, min_leaf, subsample, colsample, newton, lambda, gamma, seed, fold, n_fold, threads) {
  .Call(`_timesift_ts_boost_fit_`, x, y, w, n, p, family, trees, depth, shrinkage, min_leaf, subsample, colsample, newton, lambda, gamma, seed, fold, n_fold, threads)
}

ts_boost_predict_ <- function(fit, newx, n, p) {
  .Call(`_timesift_ts_boost_predict_`, fit, newx, n, p)
}

ts_forest_stream_ <- function(seed, tree, n) {
  .Call(`_timesift_ts_forest_stream_`, seed, tree, n)
}

ts_maxnet_design_ <- function(x, y, n, p, classes, knots, regmult, formulation, add_samples, max_design) {
  .Call(`_timesift_ts_maxnet_design_`, x, y, n, p, classes, knots, regmult, formulation, add_samples, max_design)
}

ts_maxnet_fit_ <- function(x, y, w, n, p, classes, knots, regmult, formulation, add_samples, thresh, max_pass, n_lambda, one_se, fold, n_fold, threads, max_design) {
  .Call(`_timesift_ts_maxnet_fit_`, x, y, w, n, p, classes, knots, regmult, formulation, add_samples, thresh, max_pass, n_lambda, one_se, fold, n_fold, threads, max_design)
}

ts_maxnet_predict_ <- function(fit, newx, n, p, clamp, type) {
  .Call(`_timesift_ts_maxnet_predict_`, fit, newx, n, p, clamp, type)
}

ts_envelope_fit_ <- function(x, y, n, p, quantile) {
  .Call(`_timesift_ts_envelope_fit_`, x, y, n, p, quantile)
}

ts_envelope_predict_ <- function(fit, newx, n, p) {
  .Call(`_timesift_ts_envelope_predict_`, fit, newx, n, p)
}

ts_stepwise_fit_ <- function(x, y, w, n, p, family, max_terms, degree, direction, terms, threads) {
  .Call(`_timesift_ts_stepwise_fit_`, x, y, w, n, p, family, max_terms, degree, direction, terms, threads)
}

ts_stepwise_predict_ <- function(fit, newx, n, p) {
  .Call(`_timesift_ts_stepwise_predict_`, fit, newx, n, p)
}

ts_mars_fit_ <- function(x, y, w, n, p, family, degree, penalty, nk, thresh, minspan, endspan, fast_k, fast_beta, prune, nprune, threads) {
  .Call(`_timesift_ts_mars_fit_`, x, y, w, n, p, family, degree, penalty, nk, thresh, minspan, endspan, fast_k, fast_beta, prune, nprune, threads)
}

ts_mars_predict_ <- function(fit, newx, n, p) {
  .Call(`_timesift_ts_mars_predict_`, fit, newx, n, p)
}

ts_perceptron_fit_ <- function(x, y, w, n, p, family, hidden, skip, decay, range, max_iter, abs_tol, rel_tol, seed, start) {
  .Call(`_timesift_ts_perceptron_fit_`, x, y, w, n, p, family, hidden, skip, decay, range, max_iter, abs_tol, rel_tol, seed, start)
}

ts_perceptron_predict_ <- function(fit, newx, n, p) {
  .Call(`_timesift_ts_perceptron_predict_`, fit, newx, n, p)
}

ts_fda_fit_ <- function(x, y, w, n, p, degree, penalty, nk, thresh, prune, calibrate, threads) {
  .Call(`_timesift_ts_fda_fit_`, x, y, w, n, p, degree, penalty, nk, thresh, prune, calibrate, threads)
}

ts_fda_predict_ <- function(fit, newx, n, p) {
  .Call(`_timesift_ts_fda_predict_`, fit, newx, n, p)
}

ts_additive_fit_ <- function(x, y, w, n, p, r, family, k, gamma, max_knots, threads, sp) {
  .Call(`_timesift_ts_additive_fit_`, x, y, w, n, p, r, family, k, gamma, max_knots, threads, sp)
}

ts_additive_predict_ <- function(fit, newx, n, p) {
  .Call(`_timesift_ts_additive_predict_`, fit, newx, n, p)
}

ts_hierarchical_fit_ <- function(x, y, w, n, p, unit, n_unit, coords, field, beta_sd, sd_u, sd_alpha, range_fraction, range_alpha, m, boundary, neighbours, cov, nodes, step, threads, theta) {
  .Call(`_timesift_ts_hierarchical_fit_`, x, y, w, n, p, unit, n_unit, coords, field, beta_sd, sd_u, sd_alpha, range_fraction, range_alpha, m, boundary, neighbours, cov, nodes, step, threads, theta)
}

ts_hierarchical_predict_ <- function(fit, newx, n, p, unit, coords) {
  .Call(`_timesift_ts_hierarchical_predict_`, fit, newx, n, p, unit, coords)
}
