# Generated by cpp11: do not edit by hand

ts_reduce_ <- function(unit, value, when, local, custom, unit_names, grain, year_month, year_day, stats, sampling_step) {
  .Call(`_timesift_ts_reduce_`, unit, value, when, local, custom, unit_names, grain, year_month, year_day, stats, sampling_step)
}

ts_coverage_ <- function(unit, when, local, custom, unit_names, grain, year_month, year_day) {
  .Call(`_timesift_ts_coverage_`, unit, when, local, custom, unit_names, grain, year_month, year_day)
}

ts_reduce_lookbacks_ <- function(unit, value, when, local, unit_names, target_unit, target_at, target_names, span, lag, bins, stats) {
  .Call(`_timesift_ts_reduce_lookbacks_`, unit, value, when, local, unit_names, target_unit, target_at, target_names, span, lag, bins, stats)
}

ts_bin_starts_ <- function(local, grain, year_month, year_day) {
  .Call(`_timesift_ts_bin_starts_`, local, grain, year_month, year_day)
}

ts_bin_nexts_ <- function(bins, grain, year_month, year_day) {
  .Call(`_timesift_ts_bin_nexts_`, bins, grain, year_month, year_day)
}

ts_year_fraction_ <- function(bin_start, bin_end) {
  .Call(`_timesift_ts_year_fraction_`, bin_start, bin_end)
}

ts_year_phase_ <- function(bin_start, bin_end) {
  .Call(`_timesift_ts_year_phase_`, bin_start, bin_end)
}

ts_penalised_path_ <- function(x, y, w, n, p, family, alpha, n_lambda, lambda_min_ratio, lambda, thresh, standardize, intercept, max_pass) {
  .Call(`_timesift_ts_penalised_path_`, x, y, w, n, p, family, alpha, n_lambda, lambda_min_ratio, lambda, thresh, standardize, intercept, max_pass)
}

ts_penalised_cv_ <- function(x, y, w, n, p, family, alpha, n_lambda, lambda_min_ratio, lambda, thresh, standardize, intercept, fold, n_fold, max_pass) {
  .Call(`_timesift_ts_penalised_cv_`, x, y, w, n, p, family, alpha, n_lambda, lambda_min_ratio, lambda, thresh, standardize, intercept, fold, n_fold, max_pass)
}

ts_penalised_predict_ <- function(lambda, a0, beta, family, at, newx, n) {
  .Call(`_timesift_ts_penalised_predict_`, lambda, a0, beta, family, at, newx, n)
}

ts_penalised_coef_ <- function(lambda, a0, beta, family, at) {
  .Call(`_timesift_ts_penalised_coef_`, lambda, a0, beta, family, at)
}
